name: CI/CD Pipeline - Build & Push to AWS ECR

# Gatilho: Executa o pipeline sempre que houver um push para a branch 'master'
on:
  push:
    branches:
      - master
  # Permite que o pipeline seja executado manualmente
  workflow_dispatch:

env:
  # Variáveis de ambiente
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: iscool-gpt-api # Nome do seu repositório ECR
  IMAGE_TAG: ${{ github.sha }} # Usa o hash do commit como tag da imagem para unicidade

jobs:
  build_and_push:
    # O pipeline roda em um ambiente Linux (ubuntu)
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configurar credenciais da AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Login no AWS ECR (Docker)
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        
      # 4. Build e Tag da Imagem Docker
      - name: Build and Tag Docker Image
        id: build-image
        run: |
          # 1234567890.dkr.ecr.us-east-1.amazonaws.com/iscool-gpt-api
          ECR_URI=${{ secrets.ECR_REPOSITORY_URI }}
          
          # Define a tag completa da imagem
          IMAGE_URI="$ECR_URI:${{ env.IMAGE_TAG }}"
          
          # Realiza o build (usando o Dockerfile que você já validou)
          docker build -t $IMAGE_URI .
          
          # Salva a URI da imagem para uso no próximo passo (Push)
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          
      # 5. Push da Imagem para o ECR
      - name: Push Docker Image to ECR
        run: |
          echo "Pushing image: ${{ env.IMAGE_URI }}"
          docker push ${{ env.IMAGE_URI }}
          echo "Successfully pushed image: ${{ env.IMAGE_URI }}"
          
      # 6. (Próxima Fase) Exporta a URI da imagem para uso em um possível step de deploy ECS
      - name: Output Image URI
        id: output_image
        outputs:
          image: ${{ env.IMAGE_URI }}
        run: echo "image_uri=${{ env.IMAGE_URI }}" >> $GITHUB_OUTPUT