name: CI/CD Pipeline - Build, Push & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: iscool-gpt-api
  ECS_CLUSTER: iscool-gpt-cluster
  ECS_SERVICE: iscool-gpt-task-definition-service
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: iscool-gpt-api

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x mvnw
      - run: ./mvnw test -Dmaven.test.failure.ignore=true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Push and Save Image URI
        run: |
          IMAGE_URI="${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          echo "Building image: $IMAGE_URI"
          
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

          echo "$IMAGE_URI" > image_uri.txt

      - name: Upload image file
        uses: actions/upload-artifact@v4
        with:
          name: image_uri
          path: image_uri.txt


  deploy_to_ecs:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download image file
        uses: actions/download-artifact@v4
        with:
          name: image_uri
          path: .

      - name: Load image uri into env
        run: |
          IMAGE_URI=$(cat image_uri.txt)
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Render Task Definition
        id: task_def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.IMAGE_URI }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task_def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
